### ISSUE TITLE
Weapon Aim Mod Does Not Appear in TTMM or its Variants

### ISSUE THREAD

**Issue by Aneutronic** [FLSoz/WeaponAimMod#1]
What the title says. I have triple checked, and Weapon Aim Mod is not in the list of available mods. The available mods by FLSoz are:

1. Armor Piercing Projectiles
2. Laser Mod
3. Patch Projectile Phasing

**Comment by FLSoz** [comment]
Intended. The TTMM version is no longer maintained, it's moving to the workshop. See the discord modding-announcement channel for details.

**Comment by Aneutronic** [comment]
~~What is it called on the workshop? I can't find it.~~
NVM. I found it. The new mod loader looks really nice.
